# -*- coding: utf-8 -*-
"""test_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q7kYYryChqXNrzmdoSHEWpLQrcck9FgU
"""

import pytest
from unittest.mock import patch, MagicMock
# run_pipeline is globally defined, no import needed

@patch("__main__.extract_from_csv")
@patch("__main__.load_to_bigquery")
def test_run_pipeline_success(mock_extract, mock_load):
    # Mock raw data output from CSV
    mock_extract.return_value = [
        {
            "ChapterID": "TX001",
            "University_Chapter": "Texas A&M",
            "City": "College Station",
            "State": "TX",
            "X": -96.334,
            "Y": 30.627
        }
    ]

    # Mock load execution
    mock_load.return_value = None

    # Run pipeline
    run_pipeline()

    # Assertions to verify functions were called sequentially
    mock_extract.assert_called_once()
    mock_load.assert_called_once()