# -*- coding: utf-8 -*-
"""test_transform.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uJZuztcxnXLZlGRow82sCN5dR_F8BJHg
"""

import pytest
import pandas as pd

def test_transform_chapters_valid_data():
    raw_data = [
        {
            "ChapterID": "FL0110",
            "University_Chapter": "Florida State University",
            "City": "Tallahassee",
            "State": "fl",
            "X": -84.304,
            "Y": 30.438
        }
    ]

    df = transform_chapters(raw_data)

    assert len(df) == 1
    assert df.iloc[0]["chapter_id"] == "FL0110"
    assert df.iloc[0]["chapter_name"] == "Florida State University"
    assert df.iloc[0]["state"] == "FL"  # Checked uppercase transformation
    assert df.iloc[0]["longitude"] == -84.304
    assert df.iloc[0]["latitude"] == 30.438

def test_transform_chapters_drops_missing_coords():
    raw_data = [
        {
            "ChapterID": "GA0020",
            "University_Chapter": "Agricultural College",
            "City": "Tifton",
            "State": "GA",
            "X": None,  # Missing coordinate should trigger drop
            "Y": 31.463
        }
    ]

    df = transform_chapters(raw_data)
    assert len(df) == 0  # Row should be filtered out during data validation