# -*- coding: utf-8 -*-
"""src_transform.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y0m-FOftdSJxLp6nq0PYsgO2JT_2GE2H
"""

# src/transform.py
import pandas as pd
from typing import Dict, Any, List

def transform_chapters(raw_data: List[Dict[str, Any]]) -> pd.DataFrame:
    """
    Transforms raw chapter data from the ArcGIS API payload into a clean structure mapping to BigQuery requirements:
    - Chapter Id
    - Chapter Name
    - City
    - State
    - Longitude & Latitude
    """
    # If raw_data comes from ArcGIS REST API JSON, each item typically has "attributes" and optionally "geometry"
    # Let's normalize it so it works seamlessly whether it's a flat dict list or an ArcGIS feature structure.
    processed_rows = []
    for item in raw_data:
        if isinstance(item, dict) and 'attributes' in item:
            attrs = item.get('attributes', {})
            geom = item.get('geometry', {})
            # Merge attributes and geometry fields into a single flat dict for DataFrame parsing
            row = {**attrs}
            if geom:
                row['X'] = geom.get('x')
                row['Y'] = geom.get('y')
            processed_rows.append(row)
        else:
            processed_rows.append(item)

    df = pd.DataFrame(processed_rows)

    # Handle column variations from source files/API payloads
    # (Checking for standard field aliases like ChapterID vs Chapter Id)
    id_col = 'ChapterID' if 'ChapterID' in df.columns else ('Chapter Id' if 'Chapter Id' in df.columns else df.columns[0])
    
    if 'University_Chapter' in df.columns:
        name_col = 'University_Chapter'
    elif 'Chapter Name' in df.columns:
        name_col = 'Chapter Name'
    elif 'ChapterName' in df.columns:
        name_col = 'ChapterName'
    else:
        name_col = df.columns[1]

    transformed = pd.DataFrame()
    transformed['chapter_id'] = df[id_col].astype(str).str.strip()
    transformed['chapter_name'] = df[name_col].astype(str).str.strip()
    transformed['city'] = df['City'].astype(str).str.strip() if 'City' in df.columns else ''
    transformed['state'] = df['State'].astype(str).str.upper().str.strip() if 'State' in df.columns else ''

    # Extract coordinates based on schema (handling X/Y or coordinate arrays or ArcGIS geometry)
    if 'X' in df.columns and 'Y' in df.columns:
        transformed['longitude'] = pd.to_numeric(df['X'], errors='coerce')
        transformed['latitude'] = pd.to_numeric(df['Y'], errors='coerce')
    elif 'longitude' in df.columns and 'latitude' in df.columns:
        transformed['longitude'] = pd.to_numeric(df['longitude'], errors='coerce')
        transformed['latitude'] = pd.to_numeric(df['latitude'], errors='coerce')
    elif 'geometry' in df.columns:
        # If parsing from GeoJSON/Geometry objects
        coords = df['geometry'].apply(lambda g: g.get('coordinates') if isinstance(g, dict) else [None, None])
        transformed['longitude'] = pd.to_numeric([c[0] if c else None for c in coords], errors='coerce')
        transformed['latitude'] = pd.to_numeric([c[1] if c else None for c in coords], errors='coerce')
    else:
        transformed['longitude'] = None
        transformed['latitude'] = None

    # Data Validation / Quality Check: Drop rows with missing critical identifiers or invalid coords
    initial_count = len(transformed)
    transformed = transformed.dropna(subset=['chapter_id', 'longitude', 'latitude'])
    dropped_count = initial_count - len(transformed)

    if dropped_count > 0:
        print(f"[WARNING] Dropped {dropped_count} rows due to missing critical fields or coordinates.")

    return transformed